server:
  port: 7777
spring:
  activemq:
    broker-url: tcp://192.168.0.132:61616
  jms:
    pub-sub-domain: true # false \u9ED8\u8BA4\u503C\uFF0C\u961F\u5217queue\uFF1Btrue\uFF0C\u4E3B\u9898topic
# \u81EA\u5B9A\u4E49\u961F\u5217/\u4E3B\u9898\u540D\u79F0
mytopic: boo-activemq-topic

myqueue: boo-activemq-queue
